import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { randomBytes } from "node:crypto";

const PROJECT_ROOT = process.cwd();
const ENV_FILE = join(PROJECT_ROOT, ".env.local");
const DEFAULT_DATABASE_URL = "postgresql://pathway:pathway@localhost:5432/pathway";
const DEFAULT_SHORTLIST = "reports/scout-products-2026-06-19.json";

type EnvMap = Record<string, string>;

function secret(bytes = 32) {
  return randomBytes(bytes).toString("base64url");
}

function parseEnvValue(value: string) {
  const trimmed = value.trim();
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

function parseEnvFile(path: string): EnvMap {
  if (!existsSync(path)) return {};
  const env: EnvMap = {};
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (!match) continue;
    env[match[1]] = parseEnvValue(match[2]);
  }
  return env;
}

function weak(value: string | undefined) {
  if (!value?.trim()) return true;
  return /change-?me|TODO|YOUR_|^placeholder$/i.test(value);
}

function updateEnvFile(updates: EnvMap) {
  const original = existsSync(ENV_FILE) ? readFileSync(ENV_FILE, "utf8") : "";
  const lines = original ? original.split(/\r?\n/) : [];
  const written = new Set<string>();
  const next: string[] = [];

  for (const line of lines) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=/);
    const key = match?.[1];
    if (key && key in updates) {
      if (!written.has(key)) {
        next.push(`${key}=${updates[key]}`);
        written.add(key);
      }
      continue;
    }
    next.push(line);
  }

  const missing = Object.keys(updates).filter((key) => !written.has(key));
  if (missing.length > 0) {
    if (next.length > 0 && next[next.length - 1] !== "") next.push("");
    next.push("# Generated by pnpm local:bootstrap");
    for (const key of missing) next.push(`${key}=${updates[key]}`);
  }

  writeFileSync(ENV_FILE, `${next.join("\n").replace(/\n+$/g, "")}\n`);
}

function ensureEnvFile() {
  const current = parseEnvFile(ENV_FILE);
  const generated: EnvMap = {};

  const defaults: EnvMap = {
    AUTH_PROVIDER: "local",
    APP_AUTH_EMAIL: "admin@example.com",
    APP_AUTH_NAME: "Pathway Local Admin",
    APP_LOCAL_USER_ID: "00000000-0000-0000-0000-000000000001",
    APP_AUTH_PASSWORD: `local_${secret(12)}`,
    APP_SESSION_SECRET: secret(48),
    DATABASE_URL: DEFAULT_DATABASE_URL,
    NEXT_PUBLIC_APP_URL: "http://localhost:3000",
    CRON_SECRET: secret(32),
    LLM_PROVIDER: "mock",
    ANTHROPIC_ENABLE_WEB_SEARCH: "0",
    MINIMAL_SCOUT_LLM_MAX: "30",
    RESEARCH_PRODUCTS_LIMIT: "30",
    RESEARCH_PRODUCTS_PER_SOURCE: "30",
    SCOUT_FETCH_TIMEOUT_MS: "15000",
  };

  for (const [key, value] of Object.entries(defaults)) {
    if (weak(current[key])) generated[key] = value;
  }

  if (Object.keys(generated).length > 0) {
    updateEnvFile(generated);
    console.log(`[local] updated .env.local (${Object.keys(generated).join(", ")})`);
  } else {
    console.log("[local] .env.local is ready");
  }

  const env = parseEnvFile(ENV_FILE);
  for (const [key, value] of Object.entries(env)) {
    if (!process.env[key] || process.env[key]?.trim() === "") {
      process.env[key] = value;
    }
  }
  return env;
}

function run(command: string, args: string[]) {
  console.log(`[run] ${command} ${args.join(" ")}`);
  const result = spawnSync(command, args, {
    cwd: PROJECT_ROOT,
    env: process.env,
    stdio: "inherit",
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function quiet(command: string, args: string[]) {
  return spawnSync(command, args, {
    cwd: PROJECT_ROOT,
    env: process.env,
    stdio: "ignore",
  }).status === 0;
}

function dbHostPort(databaseUrl: string) {
  const url = new URL(databaseUrl);
  return {
    host: url.hostname || "localhost",
    port: url.port || "5432",
  };
}

function pgReady(host: string, port: string) {
  return quiet("pg_isready", ["-h", host, "-p", port]);
}

function sleep(ms: number) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

function waitForPostgres(host: string, port: string) {
  for (let i = 0; i < 30; i++) {
    if (pgReady(host, port)) return;
    sleep(1000);
  }
  throw new Error(`Postgres did not become ready at ${host}:${port}`);
}

function startPostgresIfNeeded(databaseUrl: string) {
  const { host, port } = dbHostPort(databaseUrl);
  if (pgReady(host, port)) {
    console.log(`[local] Postgres is already accepting connections at ${host}:${port}`);
    return;
  }

  console.log(`[local] starting Postgres at ${host}:${port}`);
  if (quiet("brew", ["--version"])) {
    const started = spawnSync("brew", ["services", "start", "postgresql@16"], {
      cwd: PROJECT_ROOT,
      env: process.env,
      stdio: "inherit",
    });
    if (started.status === 0) {
      waitForPostgres(host, port);
      return;
    }
  }

  mkdirSync(join(PROJECT_ROOT, "logs"), { recursive: true });
  run("pg_ctl", [
    "-D",
    "/opt/homebrew/var/postgresql@16",
    "-l",
    join(PROJECT_ROOT, "logs", "postgres.log"),
    "start",
  ]);
  waitForPostgres(host, port);
}

function main() {
  const env = ensureEnvFile();
  const databaseUrl = env.DATABASE_URL?.trim() || DEFAULT_DATABASE_URL;

  startPostgresIfNeeded(databaseUrl);
  run("bash", ["scripts/setup-db.sh"]);
  run("pnpm", ["db:seed-minimal"]);

  if (existsSync(join(PROJECT_ROOT, DEFAULT_SHORTLIST))) {
    run("pnpm", [
      "research:import",
      "--",
      "--input",
      DEFAULT_SHORTLIST,
      "--limit",
      "30",
    ]);
  } else {
    console.log(`[local] ${DEFAULT_SHORTLIST} not found; skipping product import`);
  }

  run("pnpm", ["env:check"]);
  console.log("");
  console.log("[local] bootstrap complete");
  console.log(`  app      : ${env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}`);
  console.log(`  login    : ${env.APP_AUTH_EMAIL || "admin@example.com"}`);
  console.log("  password : APP_AUTH_PASSWORD in .env.local");
}

main();
